// ===== Wine Compass: Colors & Fonts =====
export const C = {
  bg: '#F6F4F0',
  card: '#FDFCFA',
  bd: '#E8E4DC',
  tx: '#1A1714',
  sub: '#9E9688',
  acc: '#8B6914',
  gold: '#D4AF37',
  wine: '#6B1A2B',
  red: '#B53D1F',
  green: '#2A5E3F',
};

// Category colors: [foreground, background]
export const MCC = {
  'シャンパーニュ': ['#8A7A5A', '#F7F5F0'],
  '白ワイン': ['#7A7A6A', '#F4F4F0'],
  '赤ワイン': ['#6A5058', '#F5F0F1'],
  'ロゼ': ['#8A6A6A', '#F5F0F2'],
  '日本酒': ['#7A6A54', '#F5F3EE'],
  'ビール・スピリッツ': ['#7A7068', '#F2F0ED'],
  'ソフトドリンク': ['#7A7068', '#F2F0ED'],
  // English group labels
  'All Stock': ['#6A6258', '#F0EDE8'],
  'Champagne': ['#8A7A5A', '#F7F5F0'],
  'White Wines': ['#7A7A6A', '#F4F4F0'],
  'Red Wines': ['#6A5058', '#F5F0F1'],
  'Other Wines': ['#8A6A6A', '#F5F0F2'],
  'Other Beverages': ['#7A7068', '#F2F0ED'],
};

export const F = "'DM Sans','Noto Sans JP',sans-serif";
export const SR = "'Shippori Mincho','Noto Sans JP',serif";
export const EL = "'Cormorant Garamond','DM Sans',serif";

// ===== i18n =====
export const T = {
  ja: {
    app: 'Wine Compass',
    search: 'ワイン名・生産者・ヴィンテージ...',
    allStores: '全店舗',
    allCategories: '全カテゴリ',
    inStock: '在庫あり',
    outOfStock: '在庫切れ',
    addItem: '+ 新規追加',
    import: 'Excel取込',
    export: 'CSV出力',
    trash: 'ゴミ箱',
    history: '履歴',
    settings: '設定',
    logout: 'ログアウト',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    restore: '復元',
    confirm: '確認',
    name: 'ワイン名',
    producer: '生産者',
    vintage: 'ヴィンテージ',
    region: '地域',
    appellation: 'アペラシオン',
    grape: 'ブドウ品種',
    price: '価格',
    costPrice: '仕入値',
    quantity: '在庫数',
    size: 'サイズ',
    notes: 'メモ',
    category: 'カテゴリ',
    store: '店舗',
    items: '件',
    bottle: '本',
    noResults: '該当なし',
    noData: 'データなし',
    loading: '読み込み中...',
    loginTitle: 'Wine Compass',
    loginSubtitle: 'PINを入力してください',
    page: 'ページ',
    of: '/',
    prev: '前へ',
    next: '次へ',
    total: '合計',
    adjustQty: '在庫調整',
    deleteConfirm: 'を削除しますか？',
    trashEmpty: 'ゴミ箱は空です',
    permanentDelete: '完全削除',
    importExcel: 'Excelファイルを選択',
    importPreview: 'インポートプレビュー',
    importConfirm: '取込を確定',
    created: '新規',
    updated: '更新',
    skipped: 'スキップ',
    back: '戻る',
    storeName: '店舗名',
    addStore: '+ 店舗追加',
    changePin: 'PIN変更',
    lang: 'EN',
  },
  en: {
    app: 'Wine Compass',
    search: 'Wine, producer, vintage...',
    allStores: 'All Stores',
    allCategories: 'All Categories',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    addItem: '+ Add Item',
    import: 'Import',
    export: 'CSV Export',
    trash: 'Trash',
    history: 'History',
    settings: 'Settings',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    restore: 'Restore',
    confirm: 'Confirm',
    name: 'Wine Name',
    producer: 'Producer',
    vintage: 'Vintage',
    region: 'Region',
    appellation: 'Appellation',
    grape: 'Grape',
    price: 'Price',
    costPrice: 'Cost',
    quantity: 'Qty',
    size: 'Size',
    notes: 'Notes',
    category: 'Category',
    store: 'Store',
    items: 'items',
    bottle: 'btl',
    noResults: 'No results',
    noData: 'No data',
    loading: 'Loading...',
    loginTitle: 'Wine Compass',
    loginSubtitle: 'Enter PIN',
    page: 'Page',
    of: '/',
    prev: 'Prev',
    next: 'Next',
    total: 'Total',
    adjustQty: 'Adjust Qty',
    deleteConfirm: 'Delete this item?',
    trashEmpty: 'Trash is empty',
    permanentDelete: 'Delete forever',
    importExcel: 'Select Excel file',
    importPreview: 'Import Preview',
    importConfirm: 'Confirm Import',
    created: 'Created',
    updated: 'Updated',
    skipped: 'Skipped',
    back: 'Back',
    storeName: 'Store Name',
    addStore: '+ Add Store',
    changePin: 'Change PIN',
    lang: 'JP',
  }
};

// ===== Category Grouping for Stock Accordion =====
export const CATEGORY_GROUPS = [
  { key: 'all', label: 'All Stock', labelJa: '全在庫', categoryIds: null },
  { key: 'champagne', label: 'Champagne', labelJa: 'シャンパーニュ', categoryIds: [1] },
  { key: 'white', label: 'White Wines', labelJa: '白ワイン', categoryIds: [2, 8, 9, 10, 11, 12, 13, 14] },
  { key: 'red', label: 'Red Wines', labelJa: '赤ワイン', categoryIds: [3, 15, 16, 17, 18, 19, 20] },
  { key: 'other-wine', label: 'Other Wines', labelJa: 'その他ワイン', categoryIds: [4] },
  { key: 'other-bev', label: 'Other Beverages', labelJa: 'その他飲料', categoryIds: [5, 6, 7] },
];

// ===== Helpers =====
export const fmt = (n) => n != null ? '¥' + Number(n).toLocaleString() : '';
export const vintageLabel = (v) => v ? String(v) : 'NV';
