# Katakana producer name → French/English original name mapping
# Generated for Wine Compass producer name conversion

PRODUCER_MAP = {
    # === Top producers (10+ items) ===
    "ボットゲイル": "Bott-Geyl",
    "ピエールイヴコランモレ": "Pierre-Yves Colin-Morey",
    "コント・ラフォン": "Comtes Lafon",
    "ピエールヴァンサン": "Pierre Vincent",
    "レザストレル": "Les Astrelles",
    "オリヴィエバーンスタイン": "Olivier Bernstein",
    "ピエール・オリヴィエ・ガルシア": "Pierre-Olivier Garcia",
    "メオ・カミュゼ": "Méo-Camuzet",
    "ジェローム・プレヴォー": "Jérôme Prévost",
    "シルヴァンカティアール": "Sylvain Cathiard",
    "ギベルトー": "Guiberteau",
    "ロアーニャ": "Roagna",
    "ルイナール": "Ruinart",
    "エティエンヌソゼ": "Etienne Sauzet",
    "コントリジェベレール": "Comte Liger-Belair",
    "オーギュスタン": "Augustin",
    "ジャン・マリー・フーリエ": "Jean-Marie Fourrier",
    "フランソワ・ラヴノー": "François Raveneau",
    "ピエール・ブリセ": "Pierre Brisset",
    "ソリチュード": "Solitude",
    "デュージェニー": "d'Eugénie",
    "パカレ": "Pacalet",
    "ビゾ": "Bizot",
    "プリューレロック": "Prieuré-Roch",
    "ラウル・ペレス": "Raúl Pérez",
    "ルージョ": "Roulot",
    "ストーム": "Storm",
    "アグリクール": "Agri-Coeur",
    "ラルコ": "L'Arco",
    "ユリスコラン": "Ulysse Collin",
    # === 5 items ===
    "シルヴァンパタイユ": "Sylvain Pataille",
    "ジャン・マルク・ボワイヨ": "Jean-Marc Boillot",
    "マルク・モレ": "Marc Morey",
    "ドゥラモット": "Delamotte",
    "ジェラール・ペラゾー": "Gérard Peirazeau",
    "グロ・フレール・エ・スール": "Gros Frère et Sœur",
    "ハーフ": "SKIP",  # Size indicator, not a producer
    "ウィリアム・フェーヴル": "William Fèvre",
    "デュジャック・フィス・エ・ペール": "Dujac Fils et Père",
    "ラ・ジブリオット": "La Gibryotte",
    "ブラン・ガニャール": "Blain-Gagnard",
    "シャトー・ラヤス": "Château Rayas",
    "ミレマン・ワインズ": "Mullineux",
    "ポメリー": "Pommery",
    "バターフィールド": "Butterfield",
    "グザヴィエ・モノ": "Xavier Monnot",
    "アルヌーラショー": "Arnoux-Lachaux",
    "ラファリズ・フロワサール": "Lafalise Froissart",
    # === 4 items ===
    "シャルル・ジョゲ": "Charles Joguet",
    "マルク・エブラール": "Marc Hébrart",
    "ド・ヴォギュエ": "de Vogüé",
    "ヤン・ドゥリュー": "Yann Durieux",
    "レヴェイユ": "Réveillé",
    "シモン・ビーズ": "Simon Bize",
    "テリアス・コシニャ": "Tellus Cosinha",
    "テュエ・ブフ": "Tue-Bœuf",
    "レオン・マニャン": "Rémi Magnien",  # Could also be Léon Magnin
    "グロフィエ": "Groffier",
    "フィリップ・パカレ": "Philippe Pacalet",
    "ド・モンティーユ": "de Montille",
    "ジャン・クリストフ・ガルニエ": "Jean-Christophe Garnier",
    "クリストフ・ブリチェック": "Christophe Bryczek",
    "コシュ・デュリ": "Coche-Dury",
    "ドメーヌ・ルロワ": "Domaine Leroy",
    "ボワセ": "Boisset",
    "マルセル・ラピエール": "Marcel Lapierre",
    "コンフュロン・コトティド": "Confuron-Cotétidot",
    "セバスチャン・リフォー": "Sébastien Riffault",
    "アリス・エ・オリヴィエ・ド・ムール": "Alice et Olivier de Moor",
    "クルティエ・セレクション": "Courtier Sélection",
    "ジャン・ルイ・シャヴィ": "Jean-Louis Chave",
    "プラネタ": "Planeta",
    "エマニュエル・ジブロ": "Emmanuel Giboulot",
    "ドメーヌ・ポンコツ": "Domaine Ponkotsu",
    "ド・シャソルネ": "de Chassorney",
    "アンセルム・セロス": "Anselme Selosse",
    "ラモネ": "Ramonet",
    "フーリエ": "Fourrier",
    "エレスティンマッツィニ": "Heresztyn-Mazzini",
    "ティエリー・ピュズラ": "Thierry Puzelat",
    "シャトー・ポンテカネ": "Château Pontet-Canet",
    "クリスタルム": "Crystallum",
    "ヴォルネー": "SKIP",  # Village name, not producer
    "アルマンルソー": "Armand Rousseau",
    "ジャック・セロス": "Jacques Selosse",
    "ミュレ": "Muré",
    # === 3 items ===
    "プロデュクトゥール": "Producteurs",
    "ミシェル・ノエラ": "Michel Noëllat",
    "ジョルジュ・デ・ラトゥール": "Georges de Latour",
    "ニコラ・ジョリー": "Nicolas Joly",
    "サンドランヌ": "Sandlands",
    "エリック・テクシエ": "Eric Texier",
    "プリンス・フローラン・ド・メロード": "Prince Florent de Mérode",
    "ラ・プス・ドール": "La Pousse d'Or",
    "クロード・デュガ": "Claude Dugat",
    "フィリップ・コラン": "Philippe Colin",
    "シャンソン": "Chanson",
    "ジョゼフ・ドルーアン": "Joseph Drouhin",
    "アンリ・ボワイヨ": "Henri Boillot",
    "ヴォーヌロマネ": "SKIP",  # Village name
    "ティモ": "Thymiopoulos",
    "クロスロード": "Crossroads",
    "コンフュロン": "Confuron",
    "フレデリック・コサール": "Frédéric Cossard",
    "タカヒコ": "Domaine Takahiko",
    "ルフレーヴ": "Leflaive",
    "フランソワ・ミクルスキ": "François Mikulski",
    "マルク・コラン": "Marc Colin",
    "シャトー・ムートンロートシルト": "Château Mouton Rothschild",
    "ジュリアン・メイエー": "Julien Meyer",
    "アンリ・ドゥラグランジュ": "Henri Delagrange",
    "ピエール・モレ": "Pierre Morey",
    "コンコルディア": "Concordia",
    "ギイ・アミオ": "Guy Amiot",
    "エルヴェ・シャルロパン": "Hervé Charlopin",
    "ドメーヌ・セリーヌ": "Domaine Serene",
    "ティエリー・モルテ": "Thierry Mortet",
    "メゾン・ジョゼフ・ドルーアン": "Maison Joseph Drouhin",
    "リシャール・シュルラン": "Richard Cheurlin",
    "メゾン・ルロワ": "Maison Leroy",
    "ジャン・フィリップ・フィシェ": "Jean-Philippe Fichet",
    "デュジャック": "Dujac",
    "シャトー・レオヴィル・ラスカーズ": "Château Léoville-Las Cases",
    "シャルル・エドシック": "Charles Heidsieck",
    "フィリップ・シャルロパン": "Philippe Charlopin",
    "トソ": "Toso",
    "マルセル・ダイス": "Marcel Deiss",
    "ジャニアール": "Jeanniard",
    "トラペ": "Trapet",
    "シャトー・ドゥ・ラ・マルタン": "Château de la Maltroye",
    "ミシェル・グロ": "Michel Gros",
    "ポール・ペルノ": "Paul Pernot",
    "グリオット": "Griotte",
    "クリュッグ": "Krug",
    "アンヌ・フランソワーズ・グロ": "Anne-Françoise Gros",
    "テルトル・ド・ラントネ": "Tertre de Launay",
    "ジャン・ルイ・トリイエ": "Jean-Louis Trillet",
    "ジャン・タルディ": "Jean Tardy",
    "サディ": "Sadi",
    "ニエル": "Niel",
    "キスヴィン": "Kisvin",
    "ヴァンサン・ドーヴィサ": "Vincent Dauvissat",
    "ヴェルジェ": "Verget",
    "カフェ・ド・パリ": "Café de Paris",
    "ジョセフ・ペリエ": "Joseph Perrier",
    "フランソワーズ・ベルトー": "Françoise Bertheau",
    "ジャン・マルク・ルーロ": "Jean-Marc Roulot",
    "ジャン・マルク・ミヨ": "Jean-Marc Millot",
    "ペロ・ミノ": "Perrot-Minot",
    "タカヒロ": "Takahiro",
    "ドゥ・スーザ": "de Sousa",
    "アラン・ユドロ・ノエラ": "Alain Hudelot-Noëllat",
    "ギガル": "Guigal",
    "ゴンザレス・ビアス": "González Byass",
    "テイラーズ": "Taylor's",
    "ジョルジュ・ルーミエ": "Georges Roumier",
    "フレデリック・マニャン": "Frédéric Magnien",
    "アルマン・ド・ブリニャック": "Armand de Brignac",
    "シャトー・ラ・ミッション・オーブリオン": "Château La Mission Haut-Brion",
    "シャトー・ラトゥール": "Château Latour",
    "コント・アルマン": "Comte Armand",
    "ティエリー・エ・パスカル・アンブロワーズ": "Thierry et Pascale Ambroise",
    # === 2 items ===
    "ドニ・モルテ": "Denis Mortet",
    "パトリック・ジャヴィリエ": "Patrick Javillier",
    "シャンパーニュマルゲ": "Champagne Marguet",
    "ユベール・リニエ": "Hubert Lignier",
    "ジャン・グリヴォ": "Jean Grivot",
    "アルベール・マン": "Albert Mann",
    "ジャン・マリー・ラヴノー": "Jean-Marie Raveneau",
    "マチュー・ドゥラフォン": "Mathieu Delafontan",
    "アンリ・グージュ": "Henri Gouges",
    "ピエール・アマデュー": "Pierre Amadieu",
    "レイモン・デュポンファン": "Raymond Dupont-Fahn",
    "フィリップ・エ・ヴァンサン・レシュノー": "Philippe et Vincent Lécheneaut",
    "クロード・カザル": "Claude Cazals",
    "リュシアン・ル・モワンヌ": "Lucien Le Moine",
    "マチュー・コスト": "Mathieu Coste",
    "シャトー・パルメ": "Château Palmer",
    "ミッシェル・マニャン": "Michel Magnien",
    "シャトー・デ・ジャック": "Château des Jacques",
    "シャプティエ": "Chapoutier",
    "ポワテル": "Potel",
    "レ・ゼリティエ・デュ・コント・ラフォン": "Les Héritiers du Comtes Lafon",
    "ジュリアン・シュヴェ": "Julien Sunier",
    "アルマン・ド・マイヤック": "Armand de Maillac",
    "レカイヨン": "Lecaillon",
    "カステル": "Castel",
    "アラン・グライヨ": "Alain Graillot",
    "シャトー・モンペラ": "Château Mont-Pérat",
    "ピエロ": "Pieropan",
    "プロヴィダンス": "Providence",
    "パスカル・ブシャール": "Pascal Bouchard",
    "クリスチャン・モロー": "Christian Moreau",
    "マルキ・ダンジェルヴィーユ": "Marquis d'Angerville",
    "ティボー・リジェ・ベレール": "Thibault Liger-Belair",
    "シャトー・トロタノワ": "Château Trotanoy",
    "イヴ・ボワイエ・マルトノ": "Yves Boyer-Martenot",
    "ヴァランドロー": "Valandraud",
    "ジルベール・ピク": "Gilbert Picq",
    "アンリ・フェレティグ": "Henri Felettig",
    "ベルナール・デュガ・ピィ": "Bernard Dugat-Py",
    "ユベール・ラミー": "Hubert Lamy",
    "アルベール・ビショー": "Albert Bichot",
    "シルヴィ・エスモナン": "Sylvie Esmonin",
    "ヨハネス・ツィリンガー": "Johannes Zillinger",
    "フランソワ・カリヨン": "François Carillon",
    "エレスティン": "Heresztyn",
    "コンチャイトロ": "Concha y Toro",
    "ロベール・グロフィエ": "Robert Groffier",
    "クリスチャン・ベラン": "Christian Bellang",
    "ペリエ・ジュエ": "Perrier-Jouët",
    "ブシャール・ペール・エ・フィス": "Bouchard Père et Fils",
    "エマニュエル・ルジェ": "Emmanuel Rouget",
    "テレザ・ラウッツ": "Teresa Raiz",
    "ルイ・ラトゥール": "Louis Latour",
    "ポール・ジャブレ・エネ": "Paul Jaboulet Aîné",
    "ミシェル・ジュイヨ": "Michel Juillot",
    "ルー・デュモン": "Lou Dumont",
    "プリエール": "SKIP",  # Generic term
    "フェヴレ": "Faiveley",
    "モレスタン": "Morestan",
    "ジョルジュ・ミュニュレ": "Georges Mugneret",
    "ジャン・リケール": "Jean Rijckaert",
    "フランソワ・ラマルシュ": "François Lamarche",
    "ブルーノ・クレール": "Bruno Clair",
    "ルイ・ジャド": "Louis Jadot",
    "コント・ジョルジュ・ド・ヴォギュエ": "Comte Georges de Vogüé",
    "トルショー": "Tortochot",
    "クリスティーヌ・ルルー": "Christine Leroux",
    "バタール": "Bâtard",
    "ドゥメ": "Daumet",
    "ジョゼフ・ロティ": "Joseph Roty",
    "ディジオイア・ロワイエ": "Digioia-Royer",
    "ミシェル・ガニャール": "Michel Gagnard",
    "レ・ペルドリ": "Les Perdrix",
    "マス・ド・ドマ・ガサック": "Mas de Daumas Gassac",
    "クロ・ド・ラ・ロシュ": "SKIP",  # Vineyard name
    "テール・ドレ": "Terres Dorées",
    "シャトー・オーブリオン": "Château Haut-Brion",
    "カミーユ・ジルー": "Camille Giroud",
    "トリスタン・イエスト": "Tristan Hyest",
    "バンジャマン・ルルー": "Benjamin Leroux",
    "パトリス・リオン": "Patrice Rion",
    "ニコラ・テスタール": "Nicolas Testard",
    "シャトー・モンテュス": "Château Montus",
    "ジャン・ポール・エ・ブノワ・ドロワン": "Jean-Paul et Benoît Droin",
    "ギュファンス・エイナン": "Guffens-Heynen",
    "ドメーヌ・ショウ": "Domaine Chaud",
    "アンドレ・クルエ": "André Clouet",
    "サン・コム": "Saint-Cosme",
    "サントリー": "Suntory",
    "ビュルグ": "Bürge",
    "マルク・テンペ": "Marc Tempé",
    "ラトゥール・ジロー": "Latour-Giraud",
    "エルヴェ・ケルラン": "Hervé Kerlann",
    "シャトー・タルボ": "Château Talbot",
    "ル・カズ": "Le Cas",
    "アンティノリ": "Antinori",
    "ヴァレンティーニ": "Valentini",
    "パヴィヨン": "Pavillon",
    "ルイ・ロデレール": "Louis Roederer",
    "セバスチャン・マニャン": "Sébastien Magnien",
    "アンジェロ・ガヤ": "Angelo Gaja",
    "シャンベルタン": "SKIP",  # Vineyard name
    "マジ・シャンベルタン": "SKIP",  # Vineyard name
    "フランソワラヴノー": "François Raveneau",
    "シャトー・ドゥ・ヴォーヌロマネ": "Château de Vosne-Romanée",
    "ダヴィド・デュバン": "David Duband",
    "コント・セナール": "Comte Senard",
    "エルヴェ・ルーセル": "Hervé Roussel",
    "ドメーヌ・テッタ": "Domaine Tetta",
    "ジョルジュ・ノエラ": "Georges Noëllat",
    "カルロ・ジャコーザ": "Carlo Giacosa",
    "ダニエル・バロー": "Daniel Barraud",
    "ロベール・シュヴィヨン": "Robert Chevillon",
    "ジルベール・エ・クリスティーヌ・フェレ": "Gilbert et Christine Felettig",
    "ポティネ・アンポー": "Potinet-Ampeau",
    "アルマンルソ": "Armand Rousseau",
    "シャトー・ピション・ラランド": "Château Pichon-Lalande",
    "ヴュー・テレグラフ": "Vieux Télégraphe",
    "アミオ・セルヴェル": "Amiot-Servelle",
    "フランソワ・ダレン": "François d'Allaines",
    "シャルロパン": "Charlopin",
    "ミシェル・ラファルジュ": "Michel Lafarge",
    "セリーヌ": "Serene",
    "テオドール": "Théodore",
    "マルキ・ド・ラギッシュ": "Marquis de Laguiche",
    "ニュイサンジョルジュ": "SKIP",  # Village name
    "ル・マッキオーレ": "Le Macchiole",
    "クリスチャン・クレルジュ": "Christian Clerget",
    "メゾン・ドゥ": "Maison Deux",
    "ドメーヌ・ジャイエ": "Domaine Jayer",
    "ラ・ターシュ": "SKIP",  # Vineyard name
    "シャトー・マルゴー": "Château Margaux",
    "シャルル・ノエラ": "Charles Noëllat",
    "シャトー・ディケム": "Château d'Yquem",
    "ベネディクト・エ・ステファン・ティソ": "Bénédicte et Stéphane Tissot",
    "アンベール・フレール": "Humbert Frères",
    "シャトー・レグリーズ・クリネ": "Château l'Église-Clinet",
    "サンテミリオン": "SKIP",  # Region name
    "セバスチャン・ダヴォ": "Sébastien Daviau",
    "シャプレ": "Chapelet",
    # === 1 item producers (most common ones) ===
    "タカヒコ・ナカムラ": "Takahiko Nakamura",
    "アントワーヌ・アレナ": "Antoine Arena",
    "ボノーデュマルトレ": "Bonneau du Martray",
    "ロベール・アルヌー": "Robert Arnoux",
    "マルク・クレイデンワイス": "Marc Kreydenweiss",
    "ルネ・エ・ヴァンサン・ドーヴィサ": "René et Vincent Dauvissat",
    "アンリ・ボーダン": "Henri Baudin",
    "シャルル・オードワン": "Charles Audoin",
    "セバスチャン・ソレ": "Sébastien Sorrel",
    "モンジャール・ミュニュレ": "Mongeard-Mugneret",
    "フェレ": "Felettig",
    "ドメーヌ・デュガ・ピィ": "Domaine Dugat-Py",
    "オリヴィエ・ジュアン": "Olivier Jouan",
    "クリストフ・シュヴォー": "Christophe Chevaux",
    "イヴ・キュイロン": "Yves Cuilleron",
    "ユベール・ド・モンティーユ": "Hubert de Montille",
    "コント・ド・シャンパーニュ": "Comtes de Champagne",
    "アンドレ・ボノーム": "André Bonhomme",
    "カリテラ": "Caliterra",
    "ジャック・フレデリック・ミュニエ": "Jacques-Frédéric Mugnier",
    "ショパン・グロフィエ": "Chopin-Groffier",
    "シュヴァリエ・モンラッシェ": "SKIP",  # Vineyard name
    "コント・ド・ヴォギュエ": "Comte de Vogüé",
    "ルネ・ルクレール": "René Leclerc",
    "シャトー・ローザン・セグラ": "Château Rauzan-Ségla",
    "シャトー・ラフィット・ロスチャイルド": "Château Lafite Rothschild",
    "フランソワ・コタ": "François Cotat",
    "マルク・ソレ": "Marc Sorrel",
    "フランソワ・ランプ": "François Lumpp",
    "コム・デ・グリヴ": "Comme des Grives",
    "シャトー・コス・デストゥルネル": "Château Cos d'Estournel",
    "ジャン・ニコラ・メオ": "Jean-Nicolas Méo",
    "ミュニュレ・ジブール": "Mugneret-Gibourg",
    "アドリアン・カミュゼ": "Adrien Camuzet",
    "レ・ゼキソンヌ": "Les Echansons",
    "ティエリー・ジェルマン": "Thierry Germain",
    "タケダワイナリー": "Takeda Winery",
    "オリヴィエ・バーンスタイン": "Olivier Bernstein",
    "ジャン・クロード・ラトー": "Jean-Claude Rateau",
    "ルイ・ボワイヨ": "Louis Boillot",
    "レ・カイユ": "Les Cailloux",
    "ジャン・シャルル・アブバトゥッチ": "Jean-Charles Abbatucci",
    "モンラッシェ": "SKIP",  # Vineyard name
    "ドメーヌ・ロマネ・コンティ": "Domaine de la Romanée-Conti",
    "ヴォターノ": "Votano Wine",
    "アンリ・ペロ・ミノ": "Henri Perrot-Minot",
    "シャトー・バタイエ": "Château Batailley",
    "ダニエル・ダンプ": "Daniel Dampt",
    "シャトー・ペトリュス": "Château Pétrus",
    "ジョルジュ・リニエ": "Georges Lignier",
    "クロード・ルフレーヴ": "Claude Leflaive",
    "ブリューノ・コラン": "Bruno Colin",
    "ジャイエ・ジル": "Jayer-Gilles",
    "ドメーヌ・ド・ラ・ロマネ・コンティ": "Domaine de la Romanée-Conti",
    "ベルトラン・アンブロワーズ": "Bertrand Ambroise",
    "ドミニク・コルナン": "Dominique Cornin",
    "クロ・デュ・マルキ": "Clos du Marquis",
    "ボーモン・デ・クレイエール": "Beaumont des Crayères",
    "コンブ・ダルヴォー": "SKIP",  # Lieu-dit name
    "テルランツ": "Terlan",
    "ヴォギュエ": "Vogüé",
    "フィリベール": "Philibert",
    "ジャン・フォイヤール": "Jean Foillard",
    "シャトー・デュ・クロ・ド・ヴージョ": "Château du Clos de Vougeot",
    "リニエ・ミシュロ": "Lignier-Michelot",
    "メゾン・シャンピー": "Maison Champy",
    "ジャン・ジャック・コンフュロン": "Jean-Jacques Confuron",
    "デ・ラ・ロシュ": "SKIP",  # Vineyard name
    "ナターシャ・リジンスキー": "Natacha Liginsky",
    "アンリ・マルショネ": "Henri Marionnet",
    "ルイ・ミシェル": "Louis Michel",
    "シルヴァン・ピティオ": "Sylvain Pitiot",
    "シモン・ビーズ・エ・フィス": "Simon Bize et Fils",
    "アラン・シャヴィ": "Alain Chavy",
    "カミーユ": "Camille",
    "マルク・ロワ": "Marc Roy",
    "ロベール・グリエ": "SKIP",  # Could be Château-Grillet
    "ランスロ・ピエンヌ": "Lancelot-Pienne",
    "トマ・モレ": "Thomas Morey",
    "シャンパーニュ・ランソン": "Champagne Lanson",
    "アルベール・モロ": "Albert Morot",
    "バロン・ド・ロスチャイルド": "Baron de Rothschild",
    "ジャン・ピエール・ゲラン": "Jean-Pierre Guérin",
    "コロンビア・クレスト": "Columbia Crest",
    "シャトー・バルバ": "Château de Barbe",
    "タイユヴァン": "Taillevent",
    "ヴーヴ・クリコ": "Veuve Clicquot",
    "ドメーヌ・デ・クロ": "Domaine des Croix",
    "エミール・アニック": "Emile Anick",
    "パスカル・クレメン": "Pascal Clément",
    "ドメーヌ・デュ・ペゴー": "Domaine du Pégau",
    "フランソワ・ジャン": "François Jean",
    "ルイ・シニャール": "Louis Chenu",
    "シャンドン": "Chandon",
    "テタンジェ": "Taittinger",
    "ミエ・イケノ": "Mie Ikeno",
    "ケイジ・サトウ": "Keiji Sato",
    "コンフュロンジャンド": "Confuron-Gindre",
    "ドメーヌ・レイジェベッセ": "Domaine Reyser-Besse",
    "ドメーヌ・ポティネ・アンポー": "Domaine Potinet-Ampeau",
    "ヒラカワ・ワイナリー": "Hirakawa Winery",
    "マルセナック": "Marsenach",
    "シャトー・デ・シャルム": "Château des Charmes",
    "ドメーヌ・デ・ランブレイ": "Domaine des Lambrays",
    "フィリップ・ルクレール": "Philippe Leclerc",
    "ドメーヌ・ドゥ・ラ・ヴージュレ": "Domaine de la Vougeraie",
    "シャルル・ド・カザノーヴ": "Charles de Cazanove",
    "アルベール・グリヴォー": "Albert Grivault",
    "ドメーヌ・ド・シェヴァリエ": "Domaine de Chevalier",
    "ピエール・ジョワヨ": "Pierre Gaillot",
    "ロビネリー": "La Robinerie",
    "ドメーヌ・コスト・コーマルタン": "Domaine Coste-Caumartin",
    "ジャン・リケ": "Jean Rijckaert",
    "クロ・レグリーズ": "Clos l'Église",
    "ジャンフランソワ・ガヌヴァ": "Jean-François Ganevat",
    "ジャン・ピエール・ロビノ": "Jean-Pierre Robinot",
    "クリスチャン・セラフィン": "Christian Sérafin",
    "コス・ラボリ": "Cos Labory",
    "エシェゾー": "SKIP",  # Vineyard name
    "トーマス・コリヨ": "Thomas Collardot",
    "ロビン": "Robin",
    "ル・コルトン": "SKIP",  # Vineyard name
    "プーアル　ジャスミン": "SKIP",  # Tea, not wine
    "きんせんウーロン": "SKIP",  # Tea
    "ほうおうたんそう　ミーランシャン": "SKIP",  # Tea
    "合計外・後付け追加分": "SKIP",  # Accounting label
    "合計外・別枠": "SKIP",  # Accounting label
    "参考": "SKIP",  # Reference label
    "ザコル": "Les Accoles",
    "セントゥリオン": "Centurion",
    "ロワレ": "Loiret",
    "ユドロ・バイエ": "Hudelot-Baillet",
    "シャンパーニュ": "SKIP",  # Region name
    "ドメーヌ・ペロ・ミノ": "Domaine Perrot-Minot",
    "ブシャール": "Bouchard",
    "サヴィニー": "SKIP",  # Village name
    "オリヴィエ・ルフレーヴ": "Olivier Leflaive",
    "ヴィンツェンツ・プリューガー": "Vinzenz Prüger",
    "ジャン・ルイ・ライヤール": "Jean-Louis Raillard",
    "シャトー・パプ・クレマン": "Château Pape-Clément",
    "バローロ": "SKIP",  # Region name
    "フォンテーヌ・ガニャール": "Fontaine-Gagnard",
    "シャトー・ド・ピュリニー・モンラッシェ": "Château de Puligny-Montrachet",
    "ルイ・マックス": "Louis Max",
    "カミュゼ・ペール・エ・フィス": "Camuzet Père et Fils",
    "レミ・ジョバール": "Rémi Jobard",
    "シャルル・ヴァン・カネット": "Charles Van Canneyt",
    "ペルナン・ヴェルジュレス": "SKIP",  # Village name
    "ジャン・ピエール・エ・ミシェル・ルディエ": "Jean-Pierre et Michel Rudier",
    "グランエシェゾー": "SKIP",  # Vineyard name
    "リシュブール": "SKIP",  # Vineyard name
    "ロマネ・サン・ヴィヴァン": "SKIP",  # Vineyard name
    "シャンボール・ミュジニー": "SKIP",  # Village name
    "アンドレ・ペリン": "André Perrin",
    "ガティノワ": "Gatinois",
    "シャトー・ランシュ・バージュ": "Château Lynch-Bages",
    "ロビネ": "Robinet",
    "ダミアン・マルタン": "Damien Martin",
    "ドメーヌ・ルジェ": "Domaine Rouget",
    "コート・ド・ボーヌ": "SKIP",  # Region name
    "ジャン・リュック・ジュイヨ": "Jean-Luc Joillot",
    "パトリック・ミオレーヌ": "Patrick Miolane",
    "ニコラ・フィアット": "Nicolas Feuillatte",
    "ドメーヌ・デ・ザコル": "Domaine des Accoles",
    "アラン・ビュルゲ": "Alain Burguet",
    "ドメーヌ・メイエ・フォンネ": "Domaine Meyer-Fonné",
    "フィリップ・ベルナール": "Philippe Bernard",
    "レオン・マニャン": "Léon Magnien",
    "エルベ・シャルロパン": "Hervé Charlopin",
    "コート・ド・ニュイ": "SKIP",  # Region name
    "ジャン・ドゥニ": "Jean Denis",
    "レオン・バラル": "Léon Barral",
    # === Additional mappings (4+ items) ===
    "ヴァンサン・エ・ソフィー・モレ": "Vincent et Sophie Morey",
    "アルヴィナペルノ": "Alvina Pernot",
    "アルヴィナ・ペルノ": "Alvina Pernot",
    "シャヴォスト": "Chauvost",
    "ヴァンサン・ダンセール": "Vincent Dancer",
    "ヴァンサンダンセール": "Vincent Dancer",
    "ジル・ブートン": "Gilles Bouton",
    "ジルブートン": "Gilles Bouton",
    "マルク・ソワイヤール": "Marc Soyard",
    "マルクソワイヤール": "Marc Soyard",
    "パトリック・ピウズ": "Patrick Piuze",
    "バシュレモノ": "Bachelet-Monnot",
    "ブノワモロー": "Benoît Moreau",
    "ルシアン・ボワイヨ": "Lucien Boillot",
    "ジャン・ルイ・シャーヴ": "Jean-Louis Chave",
    "ヴァンサン・ジラルダン": "Vincent Girardin",
    "ヴァンサンジラルダン": "Vincent Girardin",
    "イヴォン・クレルジェ": "Yvon Clerget",
    "イヴォンクレルジェ": "Yvon Clerget",
    "カロリーヌモレ": "Caroline Morey",
    "カロリーヌ・モレ": "Caroline Morey",
    "ブレンダーステイターウエスト": "Brendan Stater-West",
    "ブレンダン・ステイター・ウェスト": "Brendan Stater-West",
    "ピエリック・ブレ": "Pierrick Bouley",
    "ジラール・ボネ": "Girard-Bonnet",
    "ジュゼッペ・クインタレッリ": "Giuseppe Quintarelli",
    "ジュゼッペクインタレッリ": "Giuseppe Quintarelli",
    "フォントディ": "Fontodi",
    "フランソワミエ": "François Miét",
    "平川ワイナリー": "Hirakawa Winery",
    "テヌータ・デル・オルネライア": "Tenuta dell'Ornellaia",
    "トロ・アルバラ": "Toro Albalá",
    "シネ・クア・ノン": "Sine Qua Non",
    "フランツ・ケラー": "Franz Keller",
    "ラ・ロジェリー": "La Rogerie",
    "ラロジェリー": "La Rogerie",
    "ビービー・グラーツ": "Bibi Graetz",
    "アルヘイト・ヴィンヤーズ": "Alheit Vineyards",
    "セサール・マルケス": "César Márquez",
    "ルチアーノ・サンドローネ": "Luciano Sandrone",
    "マーカス・モリトール": "Markus Molitor",
    "ルフレーヴ(エスプリ)": "Leflaive (Esprit)",
    "ピエール・イヴ・コラン・モレ": "Pierre-Yves Colin-Morey",
    "アンリ・グージュ(メゾン)": "Henri Gouges (Maison)",
    "アンリ・ボワイヨ(ドメーヌ)": "Henri Boillot (Domaine)",
    "アンリボワイヨ": "Henri Boillot",
    # === Additional 3-item producers ===
    "ガニャール・ドラグランジュ": "Gagnard-Delagrange",
    "ラモネ・ノエル": "Ramonet-Noël",
    "ラモネノエル": "Ramonet-Noël",
    "オー・モワンヌ": "Haut-Moines",
    "オーモワンヌ": "Haut-Moines",
    "トレヴァロン": "Trevallon",
    "アンリノーダンフェラン": "Henri Naudin-Ferrand",
    "マルキダンジェルヴィーユ": "Marquis d'Angerville",
    "マルキ・ダンジュルヴィーユ": "Marquis d'Angerville",
    "アルノー・エ・ソフィー・シリュグ・ノエラ": "Arnaud et Sophie Sirugue-Noëllat",
    "アルノーエソフィーシリュグノエラ": "Arnaud et Sophie Sirugue-Noëllat",
    "ラエルト・フレール": "Laherte Frères",
    "ムーラン・ド・ガサック": "Moulin de Gassac",
    "シャトー・ラフィット・ロートシルト": "Château Lafite Rothschild",
    "ミッシェル・グロ": "Michel Gros",
    "セイズファーム": "Seifried Estate",
    "トプノ・メルム": "Taupenot-Merme",
    "トプノメルム": "Taupenot-Merme",
    "アルノー・バイヨ": "Arnaud Baillot",
    "ペゴー": "Pégau",
    "ジェラール・ベルトラン": "Gérard Bertrand",
    "グザヴィエ・ジェラール": "Xavier Gérard",
    "グザヴィエジェラール": "Xavier Gérard",
    "デゾネイビセイ": "Desaunay-Bissey",
    "ブリューノ・デゾネイ・ビセイ": "Bruno Desaunay-Bissey",
    "デゾネイ・ビセイ": "Desaunay-Bissey",
    "ジェローム・ガレラン": "Jérôme Galeyrand",
    "ジェロームガレラン": "Jérôme Galeyrand",
    "バルメス・ブシェール": "Barmès-Buecher",
    "ギヨーム・セロス": "Guillaume Selosse",
    "ギョーム・セロス": "Guillaume Selosse",
    "エマニュエル・ブロシェ": "Emmanuel Brochet",
    "エマニュエルブロシェ": "Emmanuel Brochet",
    "マリー・ドゥメ": "Marie Daumet",
    "ロック・ブレイア": "Roc Breia",
    "ジュールブロシェ": "Jules Brochet",
    "ジュール・ブロシェ": "Jules Brochet",
    "ギルベールジレ": "Gilbert et Christine Felettig",
    "スクリーミング・イーグル": "Screaming Eagle",
    "スクリーミングイーグル": "Screaming Eagle",
    "スタッグスリープ・ワイン・セラーズ": "Stag's Leap Wine Cellars",
    "スタッグス・リープ・ワイン・セラーズ": "Stag's Leap Wine Cellars",
    "スタッグスリープ": "Stag's Leap Wine Cellars",
    "ベガ・シシリア": "Vega Sicilia",
    "ベガシシリア": "Vega Sicilia",
    "ゴビー": "Gauby",
    "ベレーヌ": "Bélène",
    "プリミティーボ・コリャンテス": "Primitivo Collantes",
    "エリック・モルガ": "Éric Morgat",
    "エリックモルガ": "Éric Morgat",
    "ゴノン": "Gonon",
    "ピエールゴノン": "Pierre Gonon",
    "ピエール・ゴノン": "Pierre Gonon",
    "ラ・パルセル": "La Parcelle",
    "ポール・ホブス": "Paul Hobbs",
    "モレル": "Morel",
    "アグラパール(パスカル)": "Agrapart (Pascal)",
    "ユベールラミー": "Hubert Lamy",
    "ベルナール・ボードリー": "Bernard Baudry",
    "ベルナールボードリー": "Bernard Baudry",
    "ベリヴィエール": "Bellivière",
    "ドメーヌフーリエ": "Domaine Fourrier",
    "ド・ヴェルニュス": "de Vernus",
    "ラルマンディエ・ベルニエ": "Larmandier-Bernier",
    "ラルマンディエベルニエ": "Larmandier-Bernier",
    "パッツ・アンド・ホール": "Patz & Hall",
    "ギュファンエナン": "Guffens-Heynen",
    "ミーゴダール": "Mee Godard",
    "ミー・ゴダール": "Mee Godard",
    "ベルナール・ボナン": "Bernard Bonin",
    "ラ・グランジュ・ド・ロンクル・シャルル": "La Grange de l'Oncle Charles",
    "ラグランジュドロンクルシャルル": "La Grange de l'Oncle Charles",
    # === Additional 2-item producers ===
    "アントワーヌリエナルト": "Antoine Lienhardt",
    "アントワーヌ・プティプレ": "Antoine Petitprez",
    "ロレ": "Rollet",
    "パルランジュ・エ・イルーズ": "Parlange et Illouz",
    "パルランジュエイルーズ": "Parlange et Illouz",
    "カミーユティリエ": "Camille Thiriet",
    "セシルトランブレイ": "Cécile Tremblay",
    "ペロミノ": "Pero-Mino",
    "ドラピエ": "Drappier",
    "ブノワ・ライエ": "Benoît Lahaye",
    "ブノワライエ": "Benoît Lahaye",
    "セギノ・ボルデ": "Séguinot-Bordet",
    "アランユドロノエラ": "Alain Hudelot-Noëllat",
    "ジャック・カシュー": "Jacques Cacheux",
    "ジャックカシュー": "Jacques Cacheux",
    "フルーロ・ラローズ": "Fleurot-Larose",
    "フルーロラローズ": "Fleurot-Larose",
    "ラ・メゾン・ラブリュイエール・プリウール": "La Maison Labruyère-Prieur",
    "シャトー・レ・トロワ・クロワ": "Château Les Trois Croix",
    "ディディエ・アミオ": "Didier Amiot",
    "クロ・ド・タール": "Clos de Tart",
    "クロドタール": "Clos de Tart",
    "クロ・ド・タール(モメサン)": "Clos de Tart (Mommessin)",
    "ニコルラマルシュ": "Nicole Lamarche",
    "ランブレイ": "Lambrays",
    "エスプリ・ルフレーヴ": "Esprit Leflaive",
    "ルフレーヴ・エ・アソシエ": "Leflaive et Associés",
    "ルフレーヴアソシエ": "Leflaive et Associés",
    "ジュール・ラサール": "Jules Lassalle",
    "アンリ・ジロー": "Henri Giraud",
    "アンリジロー": "Henri Giraud",
    "マニエール": "Manière",
    "ジョルジュ・ジャイエ": "Georges Jayer",
    "ポール・グロ": "Paul Gros",
    "ジェロボーム・プレヴォー": "Jeroboam Prévost",
    "フレデリック・エスモナン": "Frédéric Esmonin",
    "ルシアン・ル・モワンヌ": "Lucien Le Moine",
    "ドニモルテ": "Denis Mortet",
    "ジェラールシュレール": "Gérard Schueller",
    "ドメーヌ・ド・ラ・ロマネコンティ": "Domaine de la Romanée-Conti",
    "ルクレール・ブリアン": "Leclerc Briant",
    "パルタジェジルベルリオーズ": "Partagé Gilles Berlioz",
    "パルタジェ・ジル・ベルリオーズ": "Partagé Gilles Berlioz",
    "ドメーヌ・ビゾ": "Domaine Bizot",
    "ジョセフロティ": "Joseph Roty",
    "ダリオ・プリンチッチ": "Dario Princic",
    "ダリオプリンチッチ": "Dario Princic",
    "ヴォターノ・ワイン": "Votano Wine",
    "アンリ・ゲナール": "Henri Guénard",
    "シルヴァン・ビジコット": "Sylvain Bzikot",
    "シルヴァン・ブジコット": "Sylvain Bzikot",
    "コンテス・ド・シェリゼ": "Comtesse de Chérisey",
    "コンテスドシェリゼ": "Comtesse de Chérisey",
    "コントドシャペル": "Comte de Chapelle",
    "フィリップ・エ・アンリ・ジュアン": "Philippe et Henri Jouan",
    "ジェラール・ジュリアン": "Gérard Julien",
    "ジェラールジュリアン": "Gérard Julien",
    "オーパス・ワン": "Opus One",
    "オーパスワン": "Opus One",
    "ザ・サディ・ファミリー・ワインズ": "The Sadie Family Wines",
    "サディファミリー": "The Sadie Family Wines",
    "クスダ": "Kusuda",
    "レジス・ミネ": "Régis Minet",
    "レア": "Réa",
    "ジュリアンプレラ": "Julien Prélat",
    "ジュリアン・プレラ": "Julien Prélat",
    "ピエール・フリック": "Pierre Frick",
    "ヒューゲル": "Hugel",
    "クリストフ・ルーミエ": "Christophe Roumier",
    "ジャン・クロード・バシュレ": "Jean-Claude Bachelet",
    "デュジェニー": "d'Eugénie",
    "ピエール・ジラルダン": "Pierre Girardin",
    "ユエ": "Huet",
    "ヴァンソン・クーシュ": "Vincent Couche",
    "ニコラ・ルナール(シャトー・ド・ゴール)": "Nicolas Renard (Château de Gaure)",
    "ティボー・ブーディニョン": "Thibaud Boudignon",
    "ティボーブーディニョン": "Thibaud Boudignon",
    "クインテッサ": "Quintessa",
    "ファブリス・ヴィゴ": "Fabrice Vigot",
    "サヴァール": "Savart",
    "フレデリックサヴァール": "Frédéric Savart",
    "ドメーヌポンコツ": "Domaine Ponkotsu",
    "ドメーヌ・ゲイラール": "Domaine Gaillard",
    "ボテガス・トロ・アルバラ": "Bodegas Toro Albalá",
    "スェナン": "Suenen",
    "ビノーム": "Binome",
    "マルグリット・ギュイヨ": "Marguerite Guillot",
    "ピエールペテルス": "Pierre Péters",
    "デルガド・スレタ": "Delgado Zuleta",
    "プラーガー": "Prager",
    "ファミーユジョリー": "Famille Joly",
    "ファミーユ・ペラン": "Famille Perrin",
    "ローズドジャンヌ": "Roses de Jeanne",
    "ミカエルブール": "Mikaël Bouges",
    "テオ・ダンセール": "Théo Dancer",
    "サヴェージ": "Savage",
    "ド・ラ・ノブレ": "de la Noble",
    "シャトー・オー・ブリオン": "Château Haut-Brion",
    "クロ・デュ・モン・オリヴェ": "Clos du Mont-Olivet",
    "モローノーデ": "Moreau-Naudet",
    "アリスエオリヴィエドムール": "Alice et Olivier de Moor",
    "ミシェル・ジュネ": "Michel Junet",
    "ミッシェル・ジュネ": "Michel Junet",
    "ミシェルジュネ": "Michel Junet",
    "ミレマンワインズ": "Mullineux",
    "ミルマンワインズ": "Mullineux",
    "ミルマン・ワインズ": "Mullineux",
    "バーベイト": "Barbeito",
    "ニーポート": "Niepoort",
    "エンビナーテ": "Envínate",
    "ジュール・デジュルネイ": "Jules Desjourneys",
    "ファミーユ・コルディエ": "Famille Cordier",
    "レ・ドゥエ・テッレ": "Le Due Terre",
    "レドゥエテッレ": "Le Due Terre",
    "ヴェット・エ・ソルベ": "Vouette et Sorbée",
    "ヴェットエソルベ": "Vouette et Sorbée",
    "ブノワアント": "Benoît Ente",
    "ダブル・ゼロ・ワインズ": "00 Wines",
    "００ワインズ": "00 Wines",
    "ショオ": "Chaud",
    "メゾンテルセ": "Maison Tercé",
    "グラヴナー": "Gravner",
    "ニコラ・マイヤール": "Nicolas Maillart",
    # === Additional 1-item producers (common names) ===
    "アルマヴィーヴァ": "Almaviva",
    "タンピエ": "Tempier",
    "ラ・トゥール・デュ・ボン": "La Tour du Bon",
    "ヴージュレ": "Vougeraie",
    "ジュルジュ・ルーミエ": "Georges Roumier",
    "ベルサン": "Bersan",
    "ファビアン・コシュ": "Fabien Coche",
    "ゴビヤール": "Gobillard",
    "マウントブレーヴ": "Mount Brave",
    "マウント・ブレーヴ": "Mount Brave",
    "アラン・マティアス": "Alain Mathias",
    "ルイ・モロー": "Louis Moreau",
    "ウィリアム・フェーブル": "William Fèvre",
    "ウィリアムフェーブル": "William Fèvre",
    "ローランラヴァントゥルー": "Laurent Lavantureaux",
    "ローラン・ラヴァントゥルー": "Laurent Lavantureaux",
    "フィリップ・ル・アルディ": "Philippe le Hardi",
    "バンジャマン・ロブロ": "Benjamin Roblet",
    "テッタ": "Tetta",
    "ジャン・マルク・モレ": "Jean-Marc Morey",
    "マルクモレ": "Marc Morey",
    "ポール・ピヨ": "Paul Pillot",
    "ポールペルノ": "Paul Pernot",
    "ピュイッソン・シャルル": "Puisson Charles",
    "ベルテ・ボンデ": "Berthe Bondet",
    "シャトー・ムートン・ロートシルト": "Château Mouton Rothschild",
    "サン・プレフェール": "Saint-Préfert",
    "イザベル・フェランド(サン・プレフェール)": "Isabelle Ferrando (Saint-Préfert)",
    "ル・ヴュー・ドンジョン": "Le Vieux Donjon",
    "ル・ヴュー・ドン・ジョン": "Le Vieux Donjon",
    "シャトー・ド・ボーカステル": "Château de Beaucastel",
    "トマ・ピュエシャヴィ": "Thomas Puéchavy",
    "トマピュエシャヴィ": "Thomas Puéchavy",
    "イアゴ・ビタリシュヴィリ": "Iago Bitarishvili",
    "二コラ・ジョリー": "Nicolas Joly",
    "フェブレ": "Faiveley",
    "ラペ": "Rapet",
    "クリスチャンベラン": "Christian Bellang",
    "ダルレイ": "D'Arlay",
    "ジェーン・エア": "Jane Eyre",
    "ジャン・リュック・ムイヤール": "Jean-Luc Mouillard",
    "ロワイエ": "Royer",
    "アンリ・ビリオ": "Henri Billiot",
    "ジョゼ・ミシェル": "José Michel",
    "クドレイ・ビゾ": "Coudray-Bizot",
    "デュロシェ": "Duroche",
    "クロードデュガ": "Claude Dugat",
    "シプリアン・アルロー": "Cyprien Arlaud",
    "ユーゴ・エ・ポーリーヌ・ヴィラ": "Hugo et Pauline Villa",
    "オリオル": "Oriol",
    "ジャナス": "Janasse",
    "セドリックブシャール": "Cédric Bouchard",
    "ダヴィッドレクラパール": "David Léclapart",
    "シャトー・リフ": "Château Riefl",
    "ジャックプリウール": "Jacques Prieur",
    "アミオ・ギィー": "Amiot-Guy",
    "アミオギィ": "Amiot-Guy",
    "アミオ・ギィ": "Amiot-Guy",
    "シャトー・コスデストゥルネル": "Château Cos d'Estournel",
    "シャトーコスデストゥルネル": "Château Cos d'Estournel",
    "リッジ": "Ridge",
    "バロ・ミヨ": "Ballot-Millot",
    "グザヴィエモノ": "Xavier Monnot",
    "ピエール・ボワッソン": "Pierre Boisson",
    "レイモン・デュポン・ファン": "Raymond Dupont-Fahn",
    "メゾンルロワ": "Maison Leroy",
    "ジャンマリーブーズロー": "Jean-Marie Bouzereau",
    "レ・モン・フルノワ": "Les Monts Fournois",
    "デュ・セリエ・オ・モワンヌ": "du Cellier aux Moines",
    "エドゥアールドロネー": "Édouard Delaunay",
    "メオカミュゼ": "Méo-Camuzet",
    "ブルーノパイヤール": "Bruno Paillard",
    "シャルル・ラショー": "Charles Lachaux",
    "シャルロパン・ティシエ": "Charlopin-Tissier",
    "ミッシェル・ゴヌー": "Michel Gaunoux",
    "バロン・ド・ラドゥセット": "Baron de Ladoucette",
    "ラドゥセット": "Ladoucette",
    "バスフィリップ": "Bass Phillip",
    "ジョセフ・コラン": "Joseph Colin",
    "ジョゼフ・コラン": "Joseph Colin",
    "シルヴァン・ロワシェ": "Sylvain Loichet",
    "メゾン・ド・モンティーユ": "Maison de Montille",
    "ジャンマルクルーロ": "Jean-Marc Roulot",
    "プスドール": "Pousse d'Or",
    "ラ・プスドール": "La Pousse d'Or",
    "レ・カイユ・ド・パラディ": "Les Cailloux du Paradis",
    "アンヌ・グロ": "Anne Gros",
    "ジャン・グリヴォー": "Jean Grivot",
    "フェルムドラサンソニエール": "Ferme de la Sansonnière",
    "ガングロフ": "Gangloff",
    "ベルナール・モロー": "Bernard Moreau",
    "ル・グラッパン": "Le Grappin",
    "ドゥセル": "Duseigneur",
    "ヴァインバック": "Weinbach",
    "マッツェイ": "Mazzei",
    "モンジャール・ミュヌレ": "Mongeard-Mugneret",
    "モンジャールミニュレ": "Mongeard-Mugneret",
    "パスカル・リオン": "Pascal Rion",
    "エコノム": "Économe",
    "アミューズブーシュ": "Amuse Bouche",
    "モンテグード": "Montegudo",
    "クロドラブリュイエール": "Clos de la Bruyère",
    "クロ・ド・ラ・ブリュイエール": "Clos de la Bruyère",
    "ヴィーニュ・ド・パラディ": "Vigne de Paradis",
    "カステラーレ・ディ・カステッリーナ": "Castellare di Castellina",
    "ルグランラトゥール": "Le Grand Latour",
    "ルグラン・ラトゥール": "Le Grand Latour",
    "オーディンスタール": "Audinsthal",
    "ヴァイダー・マルベルグ": "Veyder-Malberg",
    "ダル・フォルノ・ロマーノ": "Dal Forno Romano",
    "リジエ": "Ligier",
    "イ・ヴィニェーリ": "I Vigneri",
    "エグリーウーリエ": "Egly-Ouriet",
    "ビュルクリン・ヴォルフ": "Bürklin-Wolf",
    "アントニオ・マデイラ": "António Madeira",
    "ニコラスジェイ": "Nicolas Jay",
    "ケリーフォックス": "Kelley Fox",
    "アンドレ・ボノム": "André Bonhomme",
    "ラーモレ": "L'Amore",
    "デニス": "Denis",
    "ヨハンヨゼフプリュム": "Joh. Jos. Prüm",
    "モレッラ": "Morella",
    "クリスチャン・デュクルー": "Christian Ducroux",
    "ザ・ヒルト": "The Hilt",
    "テスタロンガ": "Testalonga",
    "ラウルぺレス": "Raúl Pérez",
    "ラウル・ぺレス": "Raúl Pérez",
    "ドメーヌ・ドゥ・ラ・シャペル": "Domaine de la Chapelle",
    "シャンプティエ": "Chapoutier",
    "ルミジール": "Remizières",
    "イミッヒ・バッテリーベルク": "Immich-Batterieberg",
    "ネオ・ブルー・ディスティラリー": "Neo Blue Distillery",
    "ネオ・ブルーディストラリー": "Neo Blue Distillery",
    "モンテスキウス": "Montesquieu",
    "シャトー・サン・ミッシェル": "Château Ste. Michelle",
    "ベッカー": "Becker",
    "ブノワ・デウ": "Benoît Deus",
    "シャパーズ": "Shappers",
    "ペンフォールズ": "Penfolds",
    "ジェラールペラゾー": "Gérard Peirazeau",
    "エルヴェジュスタン": "Hervé Justin",
    "アキレ": "Achillée",
    "ジャン・ルイ・シャーヴ・セレクション": "Jean-Louis Chave Sélection",
    "ミシェル&ステファン・オジェ": "Michel & Stéphane Ogier",
    "シャトーデトゥール": "Château des Tours",
    "シャトー・デ・トゥール": "Château des Tours",
    "ジョルジュヴェルネ": "Georges Vernay",
    "ズラブ・トプリゼ": "Zurab Topuridze",
    "フィリップ・リヴェラ": "Philippe Rivera",
    "アダム": "Adam",
    "オスピス・ド・ボーヌ(コシュ・デュリ)": "Hospices de Beaune (Coche-Dury)",
    "ルイロデレール": "Louis Roederer",
    "アンドレ・ペレ": "André Perret",
    "ザヴィエ・ジェラール": "Xavier Gérard",
    "ポール・ロジェ": "Pol Roger",
    "ヴァンサンゴードリー": "Vincent Gaudry",
    "ダイアトム": "Diatom",
    "シャトー・ルナール": "Château Reynard",
    "シードル・リー・ド・ヴェルズィ": "Cidre Lie de Verzy",
    "アレックスモロー": "Alex Moreau",
    "ミシェルニーヨン": "Michel Niellon",
    "シルヴァンモレ": "Sylvain Morey",
    "シャトー・クーテ": "Château Coutet",
    "シャトー・サン・フロラン": "Château Saint-Florent",
    "シャトー・マロット": "Château Malotte",
    "シャトー・ラグランジュ": "Château Lagrange",
    "シャトー・ラフォン・ロシェ": "Château Lafon-Rochet",
    "ドーヴィサカミュ": "Dauvissat-Camus",
    "ビヨー・シモン": "Billiot-Simon",
    "ファン・フォルクセン": "Van Volxem",
    "ヴァンサン・ロワイエ": "Vincent Royer",
    "ルフレーヴ・アソシエ": "Leflaive et Associés",
    "ピエール・エ・マリアンヌ・デュロシェ": "Pierre et Marianne Duroche",
    "ティエリーモルテ": "Thierry Mortet",
    "ロベールグロフィエ": "Robert Groffier",
    "ロバート・モンダヴィ": "Robert Mondavi",
    "ロバートモンダヴィ": "Robert Mondavi",
    "シャルリエ": "Charlier",
    "ジャン・マルク・セレック": "Jean-Marc Sélèque",
    "マインクラング": "Meinklang",
    "ゴギタ・マカリゼ": "Gogita Makaridze",
    "ラマズ・ニコラゼ": "Ramaz Nikoladze",
    "シャトー・ブラネール・デュクリュ": "Château Branaire-Ducru",
    "ゴッセ": "Gosset",
    "イル・ヴィニャイオーロ・ディ・トオル・オイカワ": "Il Vignaiolo di Toor Oikawa",
    "ウニコ・ゼロ": "Unico Zero",
    "ブロヴィア": "Brovia",
    "エドアルド・ヴァレンティーニ": "Edoardo Valentini",
    "カステッロ・ディ・ランポッラ": "Castello di Rampolla",
    "ジャックフレデリックミニュエ": "Jacques-Frédéric Mugnier",
    "デュジャックフィスエペール": "Dujac Fils et Père",
    "ベルトラン・アクセル・マーシャル・ド・グラモン": "Bertrand Axel Maréchal de Gramont",
    "アンリグージュ": "Henri Gouges",
    "ジャック・フレデリック・ミニュエ": "Jacques-Frédéric Mugnier",
    "シュヴィヨン": "Chevillon",
    "クリスチャンチダ": "Christian Chida",
    "パソ・デ・ルビアネス": "Pazo de Rubianes",
    "パルメイヤー": "Pahlmeyer",
    "ポデーリ・アルド・コンテルノ": "Poderi Aldo Conterno",
    "ジョットビーニ": "Giotto Bini",
    "トリンケーロ": "Trinchero",
    "エントレ・ペドラシュ": "Entre Pedras",
    "テヌータ・ディ・ビセルノ": "Tenuta di Biserno",
    "シャトー・ピニャン": "Château Peygnaud",
    "ブリュワー・クリフトン": "Brewer-Clifton",
    "ディディエダグノー": "Didier Dagueneau",
    "エー・エー・バーデンホースト": "A.A. Badenhorst",
    "ジャン・パビオ": "Jean Pabiot",
    "シルヴァン・リースト": "Sylvain Riesle",
    "エスプリ・ド・ミッシェル・ティソ": "Esprit de Michel Tissot",
    "ラ・ストッパ": "La Stoppa",
    "ラストッパ": "La Stoppa",
    "ギボラ": "Giboulot",
    "ディエボルト・ヴァロワ": "Diebolt-Vallois",
    "シャトー・ラプラニョット・ベル・ビュー": "Château Laplagnotte-Bellevue",
    "ミニュレジブール": "Mugneret-Gibourg",
    "ジョルジュルーミエ": "Georges Roumier",
    "サセッティ・リヴィオ・ペルティマリ": "Sassetti Livio Pertimali",
    "ドンフィオリーノ": "Don Fiorino",
    "ドン・フィオリーノ": "Don Fiorino",
    "ペパン": "Pepin",
    "ハイド・ド・ヴィレーヌ": "Hyde de Villaine",
    "ル・レザン・エ・ランジュ": "Le Raisin et l'Ange",
    "トラぺ": "Trapet",
    "ドメーヌブレス": "Domaine Bress",
    "ブレス": "Bress",
    "フランソワミクルスキ": "François Mikulski",
    "ラフージュ": "Lafuge",
    "ルーロ": "Roulot",
    "アントワーヌ・ル・プティ・ド・ラ・ヴィーニュ": "Antoine le Petit de la Vigne",
    "ドメーヌセレクション・コシュデュリ": "Domaine Sélection Coche-Dury",
    "ジャッキートルショー": "Jacky Tortochot",
    "カヴェア": "Kavea",
    "クリネッツ": "Klinec",
    "ローラン・ペリエ": "Laurent-Perrier",
    "トルブレック": "Torbreck",
    "サント・ロズリーヌ": "Sainte-Roseline",
    "カミーユ・ブラウン": "Camille Brown",
    "ティエリオット・ヴィンヤード": "Thieriot Vineyard",
    "コス・エ・メゾヌーヴ": "Cos et Maisonneuve",
    "ラグランジュデペール": "La Grange des Pères",
    "イングルヌック": "Inglenook",
    "シャトー・ラネッサン": "Château Lanessan",
    "ピーターマイケル": "Peter Michael",
    "オヴェット": "Ovette",
    "カルメット": "Calmel",
    "ジョーダン": "Jordan",
    "ベティッグ": "Felettig",
    "エイブリュー": "Abreu",
    "ミシェルジュネ": "Michel Junet",
    "シャトー・シャルル・ド・ゴール": "SKIP",  # Not a producer
    "グラン": "SKIP",  # Too generic
    "アルベール・グリヴォ": "Albert Grivault",
    "シャルル・ヴァン・カネ": "Charles Van Canneyt",
    "レ・カイユ": "Les Cailloux",
}
